### ISSUE TITLE
 Error to run node server.js

### ISSUE THREAD

**Issue by AlexDev1** [ajiejot/django-reactjs-boilerplate#1]
/home/dev/work/django-reactjs-boilerplate/node_modules/webpack-dev-server/lib/Server.js:35
  const validationErrors = webpack.validateSchema(optionsSchema, options);
                                   ^

TypeError: webpack.validateSchema is not a function
    at new Server (/home/dev/work/django-reactjs-boilerplate/node_modules/webpack-dev-server/lib/Server.js:35:36)
    at Object.<anonymous> (/home/dev/work/django-reactjs-boilerplate/server.js:5:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by bossajie** [comment]
what is the version of your npm and node.js?

**Comment by bossajie** [comment]
@AlexDev1 did you follow the instruction properly?
